name: AeroMetrics CI/CD

# Define quando a pipeline vai rodar (ao fazer push na main ou abrir um Pull Request)
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest # A máquina virtual do GitHub

    steps:
    # 1. Baixa o código do seu repositório
    - name: Checkout do código
      uses: actions/checkout@v3

    # 2. Prepara o Node.js
    - name: Configurar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    # 3. Instala as dependências (o Jest)
    - name: Instalar dependências
      run: npm install

    # 4. Roda os testes
    - name: Executar Testes
      run: npm test